baseURL: "https://adarshgowdaa.github.io/hugo-portfolio"
title: Annappa
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

# social:
#   twitter: pmichaillat

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: hugo-portfolio/papers/
      weight: 1
    - name: Courses - TODO
      url: .../courses/
      weight: 2
    - name: TODO
      url: .../design/
      weight: 3
    - name: Tags
      url: .../tags/
      weight: 5
    # - name: Newsletter
    #   url: https://pmichaillat.substack.com
    #   weight: 4

params:
  # description: "I am an Associate Professor of Economics at UC Santa Cruz. My research covers unemployment, economic slack, business cycles, and macroeconomic policy."
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in auctor massa"
  author: Dr. Annappa B
  # googleAnalyticsID: "{GA4}"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Dr. Annappa B
    subtitle: "Experienced Professor and Former Head of the Department of Computer Science and Engineering at National Institute of Technology Karnataka, Surathkal, INDIA with a demonstrated history of working in the higher education Institution. Well known Academician and Researcher in Computer Science & Engineering with Ph.D. and M.Tech. in Computer Science & Engineering from National Institute of Technology Karnataka and B.E. in Computer Science & Engineering, from Govt. B.D.T. College of Engineering Davangere, Karnataka. Working primarily in the areas of Cloud Computing, Data Science and Software Engineering."
    imageUrl: "./picture.jpeg"
    imageWidth: 160
    imageHeight: 160
    imageTitle: Annappa
    buttons:
      - name: Papers
        url: hugo-portfolio/papers/
      - name: Courses - TODO
        url: .../courses/
      - name: TODO
        url: .../design/ - TODO
      # - name: Newsletter
      #   url: https://pmichaillat.substack.com
  socialIcons:
    - name: CV
      url: /cv.pdf
    - name: Google Scholar
      url: https://scholar.google.co.in/citations?user=X6XzPxYAAAAJ&hl=en
    - name: Scopus
      url: https://www.scopus.com/authid/detail.uri?authorId=35179174200
    - name: Email
      url: mailto:annappa@nitk.edu.in
    - name: LinkedIn
      url: https://www.linkedin.com/in/annappa/
    - name: Office Hours
      url: /officehours/
    - name: Location
      url: /location/
    # - name: YouTube
    #   url: https://www.youtube.com/@pmichaillat
    # - name: GitHub
    #   url: https://github.com/pmichaillat?tab=repositories

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Annappa"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: false
  highlight:
    guessSyntax: true
    style: xcode
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
